#!/bin/bash

# alias cd='z'

# some more ls aliases
alias ll='ls -AlF'
alias la='ls -a'
alias mv="mv --no-clobber"
alias cp="cp --no-clobber"

mkcd() {
    mkdir -p $1 &&
        command cd $1
}

# ROS2 aliases
alias si='source install/setup.bash'
alias cb='colcon build --symlink-install --continue-on-error --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
alias ct='colcon test --event-handlers console_cohesion+'
alias cbsel='cb --packages-select'
alias rdp='rosdep install --from-paths . -y --ignore-src'
alias rrm='rm -r build/ install/ log/'
pypkgc() {
    ros2 pkg create $1 --build-type=ament_python --maintainer-name="Matthew Reese" --license="Apache-2.0" --dependencies=rclpy
}
ifcepkgc() {
    ros2 pkg create $1 --build-type=ament_cmake --maintainer-name="Matthew Reese" --license="Apache-2.0"
}

# Program aliases

if command -v batcat &>/dev/null; then
    alias bat='batcat'
fi
if command -v lazygit &>/dev/null; then
    alias lg='lazygit'
fi
# alias code='code-insiders'

if [[ $TERM == "xterm-kitty" ]]; then
    alias ssh='kitten ssh'
fi

alias tma='tmux attach || tmux'
