#!/usr/bin/env bash

#
#   This file echoes a bunch of color codes to the
#   terminal to demonstrate what's available.  Each
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a
#   test use of that color on all nine background
#   colors (default + 8 escapes).
#
#   Adapted from http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html

T='gYw' # The test text

echo -e "\n                 40m     41m     42m     43m\
    44m     45m     46m     47m"

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
    '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
    '  36m' '1;36m' '  37m' '1;37m'; do
    FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
        echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
    done
    echo
done
echo

# Attributes to test: normal, bold, italic, underline, blink, reverse

# https://en.wikipedia.org/wiki/ANSI_escape_code#Select_Graphic_Rendition_parameters
# Loop over attributes
for a in {0..25}; do
    # Print a small block with fg/bg/attr
    printf '%4sm ' "$a"
    echo -e " \e[${a}m  $T  \e[0m"
done

echo
