import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
#shell = { program = "/bin/bash", args = ["-l", "-c", "tmux attach || tmux"] }

[window]
decorations = "None"
opacity = 0.90
startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMonoNL NF", style = "Regular" }
size = 10

[cursor]
style = "Beam"

[keyboard]
bindings = [
  { key = "O", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "window.opacity=0.90"] } },
  { key = "I", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "window.opacity=1.00"] } },
]

# [bell]
# duration = 200
